"""create initial tables

Revision ID: 48499e2d0386
Revises: 
Create Date: 2026-09-01 20:10:45.712829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48499e2d0386'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('molecules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smiles', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proteins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('uniprot_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('molecule_id', sa.Integer(), nullable=False),
    sa.Column('protein_id', sa.Integer(), nullable=False),
    sa.Column('predicted_affinity', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['molecule_id'], ['molecules.id'], ),
    sa.ForeignKeyConstraint(['protein_id'], ['proteins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('proteins')
    op.drop_table('molecules')
    # ### end Alembic commands ###
